use std::collections::BTreeSet;

use rulepath_workspace::WorkspaceIndex;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InferenceResult {
    pub yaml: String,
}

#[must_use]
pub fn infer(index: &WorkspaceIndex) -> InferenceResult {
    let mut frameworks = BTreeSet::new();
    let mut data_layers = BTreeSet::new();
    let mut resources = BTreeSet::new();

    for file in &index.files {
        let text = &file.text;
        if text.contains("router.") || text.contains("app.") {
            frameworks.insert("express");
        }
        if text.contains("@router.") || text.contains("@app.") {
            frameworks.insert("fastapi");
        }
        if text.contains("ModelViewSet") || text.contains("APIView") {
            frameworks.insert("django_rest_framework");
        }
        if file.relative_path.contains("app/api/") || file.relative_path.contains("pages/api/") {
            frameworks.insert("nextjs");
        }
        if text.contains("prisma.") {
            data_layers.insert("prisma");
        }
        if text.contains("session.get") || text.contains("select(") {
            data_layers.insert("sqlalchemy");
        }
        if text.contains(".objects.") {
            data_layers.insert("django_orm");
        }
        for resource in ["Invoice", "Client", "User", "Order", "Payment"] {
            if text.contains(resource)
                || text
                    .to_ascii_lowercase()
                    .contains(&resource.to_ascii_lowercase())
            {
                resources.insert(resource);
            }
        }
    }

    InferenceResult {
        yaml: render_inferred_yaml(&frameworks, &data_layers, &resources),
    }
}

fn render_inferred_yaml(
    frameworks: &BTreeSet<&str>,
    data_layers: &BTreeSet<&str>,
    resources: &BTreeSet<&str>,
) -> String {
    let mut yaml = String::new();
    yaml.push_str(
        "# Draft generated by rulepath infer. Review before copying into .rulepath.yml.\n",
    );
    yaml.push_str("version: 1\n\n");
    yaml.push_str("profile:\n  name: internal_web_app\n\n");
    yaml.push_str("inference:\n  use_inferred_file_for_scan: false\n\n");
    yaml.push_str("detected:\n");
    yaml.push_str("  frameworks:\n");
    for framework in frameworks {
        yaml.push_str(&format!(
            "    - name: {framework}\n      confidence: medium\n"
        ));
    }
    yaml.push_str("  data_layers:\n");
    for data_layer in data_layers {
        yaml.push_str(&format!(
            "    - name: {data_layer}\n      confidence: medium\n"
        ));
    }
    yaml.push_str("\nresources:\n");
    for resource in resources {
        yaml.push_str(&format!(
            "  {resource}:\n    tenant_fields: [tenant_id, tenantId, client_id, clientId]\n    sensitive_fields: [status, amount, total, role]\n    server_owned_fields: [status, amount, total, role]\n"
        ));
    }
    yaml.push_str("\ninvariants:\n");
    yaml.push_str("  - id: inferred_scoped_resource_access\n");
    yaml.push_str("    type: scoped_resource_access\n");
    yaml.push_str("    resources:\n");
    for resource in resources {
        yaml.push_str(&format!("      - {resource}\n"));
    }
    yaml.push_str("    operations: [read, update, delete, export]\n");
    yaml.push_str("    required_scope: [tenant]\n");
    yaml.push_str("    severity: high\n");
    yaml
}
