[package]
name = "rulepath_rules"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Invariant rules and review hints for Rulepath."

[dependencies]
rulepath_config = { path = "../rulepath_config" }
rulepath_ir = { path = "../rulepath_ir" }

[lints]
workspace = true
