[package]
name = "rulepath_ir"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Common intermediate representation for Rulepath."

[dependencies]
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
