[package]
name = "rulepath_dataflow"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Route-to-sink tracing and initial IR construction for Rulepath."

[dependencies]
petgraph.workspace = true
rulepath_config = { path = "../rulepath_config" }
rulepath_ir = { path = "../rulepath_ir" }
rulepath_workspace = { path = "../rulepath_workspace" }

[lints]
workspace = true
